export default {
    CHANGE_ROUTE: 'CHANGE_ROUTE',
    ON_PLAY: 'ON_PLAY',
    FETCH_FILMS_REQUEST: 'FETCH_FILMS_REQUEST',
    FETCH_FILMS_SUCCESS: 'FETCH_FILMS_SUCCESS',   
    FETCH_FILMS_FAIL: 'FETCH_FILMS_FAIL',   
}